package com.qaverse.smart.core.event;

public enum EventType {

    EXECUTION_STARTED,

    EXECUTION_SUCCEEDED,

    EXECUTION_FAILED,

    EXECUTION_RETRY,

    EXECUTION_RECOVERED,

    VALIDATION_FAILED,
    
    OBSERVATION_STARTED,
    OBSERVATION_COMPLETED,

    VALIDATION_STARTED,
    VALIDATION_COMPLETED,

    RECOVERY_STARTED,
    RECOVERY_COMPLETED,

    DIAGNOSTIC_STARTED,
    DIAGNOSTIC_COMPLETED
}